//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace TestHarness.com.fidestin.supplier {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="supplierFactorySoap", Namespace="http://tempuri.org/")]
    public partial class supplierFactory : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback loadSOperationCompleted;
        
        private System.Threading.SendOrPostCallback loadSAvailOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOrInsertAvailabilityOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveCampaignCustomersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public supplierFactory() {
            this.Url = global::TestHarness.Properties.Settings.Default.TestHarness_com_fidestin_supplier_supplierFactory;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event loadSCompletedEventHandler loadSCompleted;
        
        /// <remarks/>
        public event loadSAvailCompletedEventHandler loadSAvailCompleted;
        
        /// <remarks/>
        public event UpdateOrInsertAvailabilityCompletedEventHandler UpdateOrInsertAvailabilityCompleted;
        
        /// <remarks/>
        public event SaveCampaignCustomersCompletedEventHandler SaveCampaignCustomersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/loadS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Supplier loadS(int supplierID) {
            object[] results = this.Invoke("loadS", new object[] {
                        supplierID});
            return ((Supplier)(results[0]));
        }
        
        /// <remarks/>
        public void loadSAsync(int supplierID) {
            this.loadSAsync(supplierID, null);
        }
        
        /// <remarks/>
        public void loadSAsync(int supplierID, object userState) {
            if ((this.loadSOperationCompleted == null)) {
                this.loadSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloadSOperationCompleted);
            }
            this.InvokeAsync("loadS", new object[] {
                        supplierID}, this.loadSOperationCompleted, userState);
        }
        
        private void OnloadSOperationCompleted(object arg) {
            if ((this.loadSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loadSCompleted(this, new loadSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/loadSAvail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public serviceAvailability loadSAvail(int servID) {
            object[] results = this.Invoke("loadSAvail", new object[] {
                        servID});
            return ((serviceAvailability)(results[0]));
        }
        
        /// <remarks/>
        public void loadSAvailAsync(int servID) {
            this.loadSAvailAsync(servID, null);
        }
        
        /// <remarks/>
        public void loadSAvailAsync(int servID, object userState) {
            if ((this.loadSAvailOperationCompleted == null)) {
                this.loadSAvailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloadSAvailOperationCompleted);
            }
            this.InvokeAsync("loadSAvail", new object[] {
                        servID}, this.loadSAvailOperationCompleted, userState);
        }
        
        private void OnloadSAvailOperationCompleted(object arg) {
            if ((this.loadSAvailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loadSAvailCompleted(this, new loadSAvailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateOrInsertAvailability", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateOrInsertAvailability(int servID, int mon, int tue, int wed, int thurs, int fri, int sat, int sun, int storeSupplierID, int weekID) {
            this.Invoke("UpdateOrInsertAvailability", new object[] {
                        servID,
                        mon,
                        tue,
                        wed,
                        thurs,
                        fri,
                        sat,
                        sun,
                        storeSupplierID,
                        weekID});
        }
        
        /// <remarks/>
        public void UpdateOrInsertAvailabilityAsync(int servID, int mon, int tue, int wed, int thurs, int fri, int sat, int sun, int storeSupplierID, int weekID) {
            this.UpdateOrInsertAvailabilityAsync(servID, mon, tue, wed, thurs, fri, sat, sun, storeSupplierID, weekID, null);
        }
        
        /// <remarks/>
        public void UpdateOrInsertAvailabilityAsync(int servID, int mon, int tue, int wed, int thurs, int fri, int sat, int sun, int storeSupplierID, int weekID, object userState) {
            if ((this.UpdateOrInsertAvailabilityOperationCompleted == null)) {
                this.UpdateOrInsertAvailabilityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrInsertAvailabilityOperationCompleted);
            }
            this.InvokeAsync("UpdateOrInsertAvailability", new object[] {
                        servID,
                        mon,
                        tue,
                        wed,
                        thurs,
                        fri,
                        sat,
                        sun,
                        storeSupplierID,
                        weekID}, this.UpdateOrInsertAvailabilityOperationCompleted, userState);
        }
        
        private void OnUpdateOrInsertAvailabilityOperationCompleted(object arg) {
            if ((this.UpdateOrInsertAvailabilityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrInsertAvailabilityCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveCampaignCustomers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SaveCampaignCustomers(int campaignID, int[] customers) {
            this.Invoke("SaveCampaignCustomers", new object[] {
                        campaignID,
                        customers});
        }
        
        /// <remarks/>
        public void SaveCampaignCustomersAsync(int campaignID, int[] customers) {
            this.SaveCampaignCustomersAsync(campaignID, customers, null);
        }
        
        /// <remarks/>
        public void SaveCampaignCustomersAsync(int campaignID, int[] customers, object userState) {
            if ((this.SaveCampaignCustomersOperationCompleted == null)) {
                this.SaveCampaignCustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveCampaignCustomersOperationCompleted);
            }
            this.InvokeAsync("SaveCampaignCustomers", new object[] {
                        campaignID,
                        customers}, this.SaveCampaignCustomersOperationCompleted, userState);
        }
        
        private void OnSaveCampaignCustomersOperationCompleted(object arg) {
            if ((this.SaveCampaignCustomersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCampaignCustomersCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Supplier {
        
        private string idField;
        
        private string destinationField;
        
        private string fbLinkField;
        
        private string fbImageField;
        
        private string twitterLinkField;
        
        private string twitterImageField;
        
        private string youTubeLinkField;
        
        private string youTubeImgField;
        
        private string mapLinkField;
        
        private string mapAPICallField;
        
        private string redeemTextField;
        
        private string tandcField;
        
        private string qrImgField;
        
        private string offerTextField;
        
        private string destLinkField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public string fbLink {
            get {
                return this.fbLinkField;
            }
            set {
                this.fbLinkField = value;
            }
        }
        
        /// <remarks/>
        public string fbImage {
            get {
                return this.fbImageField;
            }
            set {
                this.fbImageField = value;
            }
        }
        
        /// <remarks/>
        public string twitterLink {
            get {
                return this.twitterLinkField;
            }
            set {
                this.twitterLinkField = value;
            }
        }
        
        /// <remarks/>
        public string twitterImage {
            get {
                return this.twitterImageField;
            }
            set {
                this.twitterImageField = value;
            }
        }
        
        /// <remarks/>
        public string youTubeLink {
            get {
                return this.youTubeLinkField;
            }
            set {
                this.youTubeLinkField = value;
            }
        }
        
        /// <remarks/>
        public string youTubeImg {
            get {
                return this.youTubeImgField;
            }
            set {
                this.youTubeImgField = value;
            }
        }
        
        /// <remarks/>
        public string mapLink {
            get {
                return this.mapLinkField;
            }
            set {
                this.mapLinkField = value;
            }
        }
        
        /// <remarks/>
        public string mapAPICall {
            get {
                return this.mapAPICallField;
            }
            set {
                this.mapAPICallField = value;
            }
        }
        
        /// <remarks/>
        public string redeemText {
            get {
                return this.redeemTextField;
            }
            set {
                this.redeemTextField = value;
            }
        }
        
        /// <remarks/>
        public string tandc {
            get {
                return this.tandcField;
            }
            set {
                this.tandcField = value;
            }
        }
        
        /// <remarks/>
        public string qrImg {
            get {
                return this.qrImgField;
            }
            set {
                this.qrImgField = value;
            }
        }
        
        /// <remarks/>
        public string offerText {
            get {
                return this.offerTextField;
            }
            set {
                this.offerTextField = value;
            }
        }
        
        /// <remarks/>
        public string destLink {
            get {
                return this.destLinkField;
            }
            set {
                this.destLinkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class serviceAvailability {
        
        private int idField;
        
        private int monField;
        
        private int tueField;
        
        private int wedField;
        
        private int thursField;
        
        private int friField;
        
        private int satField;
        
        private int sunField;
        
        private int storeSupplierIDField;
        
        private int weekIDField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int mon {
            get {
                return this.monField;
            }
            set {
                this.monField = value;
            }
        }
        
        /// <remarks/>
        public int tue {
            get {
                return this.tueField;
            }
            set {
                this.tueField = value;
            }
        }
        
        /// <remarks/>
        public int wed {
            get {
                return this.wedField;
            }
            set {
                this.wedField = value;
            }
        }
        
        /// <remarks/>
        public int thurs {
            get {
                return this.thursField;
            }
            set {
                this.thursField = value;
            }
        }
        
        /// <remarks/>
        public int fri {
            get {
                return this.friField;
            }
            set {
                this.friField = value;
            }
        }
        
        /// <remarks/>
        public int sat {
            get {
                return this.satField;
            }
            set {
                this.satField = value;
            }
        }
        
        /// <remarks/>
        public int sun {
            get {
                return this.sunField;
            }
            set {
                this.sunField = value;
            }
        }
        
        /// <remarks/>
        public int storeSupplierID {
            get {
                return this.storeSupplierIDField;
            }
            set {
                this.storeSupplierIDField = value;
            }
        }
        
        /// <remarks/>
        public int weekID {
            get {
                return this.weekIDField;
            }
            set {
                this.weekIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void loadSCompletedEventHandler(object sender, loadSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loadSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loadSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Supplier Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Supplier)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void loadSAvailCompletedEventHandler(object sender, loadSAvailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loadSAvailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loadSAvailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public serviceAvailability Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((serviceAvailability)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateOrInsertAvailabilityCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SaveCampaignCustomersCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591